name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore AppBrix.sln --nologo --verbosity minimal
      - name: Build
        run: dotnet build AppBrix.sln --configuration Release --no-restore --nologo --verbosity minimal
      - name: Test
        shell: pwsh
        run: ./Test.ps1 -Release
